### ISSUE TITLE
user lockout prevention for login and password authentication

### ISSUE THREAD

**Issue by skakala** [grzegorzcode/GlobalConsole#1]
Hi Grzegorz
Are  You able to implement feature that will prevent user for being locked out when invalid credentials will be used for connecting to servers ? 

I mean after <number of failed logins  - f. ex. 2>  during conn connect command due to incorrect/expired
password it will be beneficial if application will stop processing further connection attempts for that credentials and notify user.

Reward is respect (I know You already have one) and bottle of beer.

**Comment by grzegorzcode** [comment]
@skakala I will handle this as soon as I can

**Comment by grzegorzcode** [comment]
@skakala  - there is a new build https://travis-ci.com/grzegorzcode/GlobalConsole/builds/101756660 which should solve this. I need a little more time to test this and merge to master. I will let you know when it's ready.

**Comment by grzegorzcode** [comment]
@skakala solution is up and ready :) please get a newest version.

**Comment by skakala** [comment]
@grzegorzcode  Fast & Furious  :D
